import type { components } from './schema';

type S = components['schemas'];

export type Project = S['ProjectOut'];
export type ProjectClass = S['ClassOut'];
export type ImageItem = S['ImageOut'];
export type ImagePage = S['ImagePageOut'];
export type Annotation = S['AnnotationOut'];
export type Job = S['JobOut'];
export type MlStatus = S['MlStatusOut'];
export type ShareInfo = S['ShareOut'];
export type FolderListing = S['FolderListingOut'];
export type ConnectedFolder = S['ConnectedFolderOut'];
export type ConnectResult = S['ConnectResultOut'];
export type FormatInfo = S['FormatOut'];
export type BatchOp = S['OpIn'];
export type OpResult = S['OpResultOut'];
export type SplitState = S['SplitOut'];
export type ShuffleResult = S['ShuffleOut'];
export type SplitName = 'train' | 'val' | 'test';
export type ImageStatus = 'todo' | 'in_progress' | 'done' | 'approved' | 'rejected';
export type ClassOp = S['ClassOpOut'];
export type OperationInfo = S['OperationOut'];
export type Health = S['HealthOut'];
export type ShapeItem = S['ShapeOut'];
export type AttrDef = S['AttrDef'];
export type RevertResult = S['RevertOut'];
export type AuthStatus = S['StatusOut'];
export type Person = S['UserOut'];
export type Member = S['MemberOut'];
export type Inbox = S['InboxOut'];
export type Comment = S['CommentOut'];
export type Activity = S['ActivityOut'];
export type Lock = S['LockOut'];
export type ApiToken = S['TokenOut'];
export type Role = 'owner' | 'manager' | 'annotator' | 'reviewer' | 'viewer';
