"""Local folder storage for uploaded images and thumbnails.

Keys are always generated by Katib (never built from a user filename), and every path is
checked to stay inside the storage root.
"""

from pathlib import Path
from typing import BinaryIO


class StoragePathError(ValueError):
    """A key resolved outside the storage root."""


class StorageTooLarge(ValueError):
    """The data being stored is over the size limit."""


class LocalStorage:
    def __init__(self, root: Path) -> None:
        self.root = root.resolve()

    def _path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        if self.root != path and self.root not in path.parents:
            raise StoragePathError("Storage key points outside the storage root.")
        return path

    def put(self, key: str, data: BinaryIO, max_bytes: int | None = None) -> None:
        """Write `data` to `key`. Raises StorageTooLarge and leaves no file if over `max_bytes`."""
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        total = 0
        try:
            with path.open("wb") as out:
                while chunk := data.read(1024 * 1024):
                    total += len(chunk)
                    if max_bytes is not None and total > max_bytes:
                        raise StorageTooLarge(f"Data is over {max_bytes} bytes.")
                    out.write(chunk)
        except StorageTooLarge:
            path.unlink(missing_ok=True)
            raise

    def open(self, key: str) -> BinaryIO:
        return self._path(key).open("rb")

    def exists(self, key: str) -> bool:
        return self._path(key).is_file()

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)

    def path(self, key: str) -> Path:
        return self._path(key)

    def url(self, key: str) -> str | None:
        return None
